version: "3.9"
services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - database_data:/var/lib/postgresql/data


volumes:
  database_data:
    driver: local

networks:
  app-network:
    driver: bridge
